In [ ]:
import pandas as pd
from supabase import create_client, ClientOptions
from dotenv import load_dotenv
import os

load_dotenv()  # Load environment variables from .env file
url = os.getenv("SUPABASE_URL")
key = os.getenv("SUPABASE_KEY")
print(url, key)

In [6]:
options = ClientOptions(schema="silver")

In [7]:
supabase = create_client(url, key, options=options)

In [11]:
response = supabase.table("courses").select("*").execute()

In [14]:
len(response.data)

1000

In [15]:
import pandas as pd
from supabase import create_client, ClientOptions
from dotenv import load_dotenv
import os

load_dotenv()  # Load environment variables from .env file
url = os.getenv("SUPABASE_URL")
key = os.getenv("SUPABASE_KEY")

# Tell the client to look in the 'silver' room
options = ClientOptions(schema="silver")
supabase = create_client(url, key, options=options)

try:
    print("Connecting to silver schema to pull all 7000+ rows...")
    
    all_data = []  # We will store all chunks of data here
    limit = 1000   # Max rows per request
    offset = 0     # Starting point

    while True:
        # Pull data in chunks using .range()
        response = supabase.table("courses").select("*").range(offset, offset + limit - 1).execute()
        
        data_chunk = response.data
        
        # If the chunk is empty, it means we've reached the end of the table
        if not data_chunk:
            break
            
        # Add the chunk to our main list
        all_data.extend(data_chunk)
        print(f"Fetched {len(all_data)} rows so far...")
        
        # Move the offset forward for the next loop (e.g., from 0 to 1000, then 2000)
        offset += limit

    # Check if we got data overall
    if all_data:
        df = pd.DataFrame(all_data)
        # Save it to your device
        df.to_csv("graduation_data_raw.csv", index=False)
        print(f"\nSuccess! All {len(df)} rows saved to graduation_data_raw.csv")
    else:
        print("Connected, but the table seems empty or RLS is blocking access.")

except Exception as e:
    print(f"Failed to pull data: {e}")

Connecting to silver schema to pull all 7000+ rows...
Fetched 1000 rows so far...
Fetched 2000 rows so far...
Fetched 3000 rows so far...
Fetched 4000 rows so far...
Fetched 5000 rows so far...
Fetched 6000 rows so far...
Fetched 7000 rows so far...
Fetched 7449 rows so far...

Success! All 7449 rows saved to graduation_data_raw.csv

In [2]:
from langchain_community.document_loaders.csv_loader import CSVLoader

file_path = "C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv"

# The CSVLoader automatically treats each row as a single "chunk" (Document)
# It includes the header names as keys so the LLM understands what the data means.
loader = CSVLoader(file_path=file_path)

# Load the data
docs = loader.load()

# Now 'docs' is a list of chunks ready to be embedded!
print(f"Created {len(docs)} chunks from the CSV.")
print(docs[0].page_content)

Created 7449 chunks from the CSV.
course_sk: 14099
source: khan_academy
source_course_key: khan_academy||https://www.khanacademy.org/economics-finance-domain/economics-personal-finance-va/x3ed8f3aede624754:economic-stabilization
canonical_url: https://www.khanacademy.org/economics-finance-domain/economics-personal-finance-va/x3ed8f3aede624754:economic-stabilization
row_hash: 7bc951928f6df514f133bea671f18464e37c649cc4e4e817005cae22ed4eb92f
title: Economic stabilization
headline: Economic stabilization
description: Economic stabilization. Provider: Khan Academy. Category: Economics & Finance.
rating: 0.0
rating_source: unavailable
num_reviews: 0
num_enrolled: 0
price_normalized: 0.0
is_free: True
instructor_name: Khan Academy
instructor_org:
image_url:
duration_hours: 0.0
level_normalized: All Levels
language_normalized: English
category: Economics & Finance
subcategory:
has_certificate: False
engagement_proxy: 0.0
completeness_score: 0.8
title_length: 22
description_length: 78
scraped_at: 2026-04-14T21:41:44.487823+00:00
bronze_ingested_at: 2026-04-14T21:41:26.92703+00:00
loaded_at: 2026-03-19T14:47:57.90376+00:00
updated_at: 2026-04-14T22:42:33.120104+00:00

In [3]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

def process_file_content( file_content:list,
                             chunk_size:int = 4000,overlap_size:int = 200):
    if not file_content:
        return [] 
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size = chunk_size,
        chunk_overlap = overlap_size,
        length_function = len,
        separators=["\n\n", "\n", " ", ""],
    )
    chunks = text_splitter.split_documents(file_content)

    return  chunks

In [4]:
chunks = process_file_content(docs)
print(f"Created {len(chunks)} chunks from the CSV.")

Created 7640 chunks from the CSV.

In [5]:
chunks

[Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 0}, page_content='course_sk: 14099\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/economics-finance-domain/economics-personal-finance-va/x3ed8f3aede624754:economic-stabilization\ncanonical_url: https://www.khanacademy.org/economics-finance-domain/economics-personal-finance-va/x3ed8f3aede624754:economic-stabilization\nrow_hash: 7bc951928f6df514f133bea671f18464e37c649cc4e4e817005cae22ed4eb92f\ntitle: Economic stabilization\nheadline: Economic stabilization\ndescription: Economic stabilization. Provider: Khan Academy. Category: Economics & Finance.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Economics & Finance\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 22\ndescription_length: 78\nscraped_at: 2026-04-14T21:41:44.487823+00:00\nbronze_ingested_at: 2026-04-14T21:41:26.92703+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 1}, page_content="course_sk: 12754\nsource: coursera\nsource_course_key: coursera||https://www.coursera.org/learn/object-oriented-programming-and-gui-with-python\ncanonical_url: https://www.coursera.org/learn/object-oriented-programming-and-gui-with-python\nrow_hash: 92687299a663f87f7d35d6d476c6634b339f2c0849bebadea5eea5e90e8273b8\ntitle: Object-Oriented Programming and GUI with Python\nheadline: Skills you'll gain : Object Oriented Programming (OOP), Object Oriented Design, Event-Driven Programming, Python Programming, User Interface (UI), Computer Programming, Human Computer Interaction, Application Development, Graphical Tools\ndescription: Skills you'll gain : Object Oriented Programming (OOP), Object Oriented Design, Event-Driven Programming, Python Programming, User Interface (UI), Computer Programming, Human Computer Interaction, Application Development, Graphical Tools\nrating: 3.7\nrating_source: user_reviews\nnum_reviews: 16\nnum_enrolled: 0\nprice_normalized: \nis_free: True\ninstructor_name: \ninstructor_org: Arizona State University\nimage_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/dd/1be159b82b4ba7bf3dc1410b4b2d5b/shutterstock_1404621860.jpg?auto=format%2C%20compress%2C%20enhance&dpr=1&w=320&h=180&fit=crop&q=50\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: computer-science\nsubcategory: \nhas_certificate: True\nengagement_proxy: 38.2\ncompleteness_score: 0.6667\ntitle_length: 47\ndescription_length: 237\nscraped_at: 2026-04-14T22:26:57.389543+00:00\nbronze_ingested_at: 2026-04-14T22:21:51.370539+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00"),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 2}, page_content='course_sk: 14102\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/math/6th-grade-math-eureka-squared-aligned\ncanonical_url: https://www.khanacademy.org/math/6th-grade-math-eureka-squared-aligned\nrow_hash: a627ae395488b1fc03548af919933cd44af443c1086f860c573e49d1d8a0576a\ntitle: 6th grade (Eureka Math Squared-aligned)\nheadline: 6th grade (Eureka Math Squared-aligned)\ndescription: 6th grade (Eureka Math Squared-aligned). Provider: Khan Academy. Category: Math.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Math\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 39\ndescription_length: 80\nscraped_at: 2026-04-14T22:37:51.405454+00:00\nbronze_ingested_at: 2026-04-14T22:37:36.68496+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 3}, page_content='course_sk: 14103\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/math/algebra-1-ny-next-gen/xd156c2c030b6ba5d:absolute-value-piecewise-functions\ncanonical_url: https://www.khanacademy.org/math/algebra-1-ny-next-gen/xd156c2c030b6ba5d:absolute-value-piecewise-functions\nrow_hash: 1d9129f9f96c50923f0ba867cb7084bb9ca28945812762b84c29866cee44ae4c\ntitle: Absolute value & piecewise functions\nheadline: Absolute value & piecewise functions\ndescription: Absolute value & piecewise functions. Provider: Khan Academy. Category: Math.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Math\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 36\ndescription_length: 77\nscraped_at: 2026-04-14T22:37:51.408885+00:00\nbronze_ingested_at: 2026-04-14T22:37:36.68496+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 4}, page_content='course_sk: 12970\nsource: coursera\nsource_course_key: coursera||https://www.coursera.org/degrees/master-of-computer-science-illinois\ncanonical_url: https://www.coursera.org/degrees/master-of-computer-science-illinois\nrow_hash: 3ecfd83bc3d1264bf295d289b075d07c71b2b21de3bf8e6b472a0868702156e5\ntitle: Master of Computer Science (feat. Data Science Track)\nheadline: Degree · 12 – 36 months\ndescription: Degree · 12 – 36 months\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: \nis_free: False\ninstructor_name: \ninstructor_org: University of Illinois at Urbana-Champaign\nimage_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/ddp/branding/illinois/Graduates_Celebrating_square.JPG?auto=format%2C%20compress%2C%20enhance&dpr=1&w=320&h=180&q=50&fit=crop\nduration_hours: 0.0\nlevel_normalized: Unknown\nlanguage_normalized: English\ncategory: data-science\nsubcategory: \nhas_certificate: True\nengagement_proxy: 0.0\ncompleteness_score: 0.6667\ntitle_length: 53\ndescription_length: 23\nscraped_at: 2026-04-14T22:17:41.629568+00:00\nbronze_ingested_at: 2026-04-14T22:14:52.089201+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 5}, page_content='course_sk: 14666\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/math/cc-fourth-grade-math/plane-figures\ncanonical_url: https://www.khanacademy.org/math/cc-fourth-grade-math/plane-figures\nrow_hash: 70113dbb9710c3436f6b6bc335fe512a6c54d0fddbe103c3644b04bdbb170e11\ntitle: Plane figures\nheadline: Plane figures\ndescription: Plane figures. Provider: Khan Academy. Category: Math.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Math\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 13\ndescription_length: 54\nscraped_at: 2026-04-14T22:37:51.334186+00:00\nbronze_ingested_at: 2026-04-14T22:37:36.68496+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 6}, page_content="course_sk: 13370\nsource: coursera\nsource_course_key: coursera||https://www.coursera.org/projects/python-for-data-analysis-numpy\ncanonical_url: https://www.coursera.org/projects/python-for-data-analysis-numpy\nrow_hash: f0b7c209bc4b741d349ef136b3f2c9bd1092129fff86735d74d1542ebcd67071\ntitle: Python for Data Analysis: Pandas & NumPy\nheadline: Skills you'll gain: Pandas (Python Package), NumPy, Data Analysis, Data Science, Python Programming, Data Structures, Exploratory Data Analysis, Data Manipulation, Computer Programming\ndescription: Skills you'll gain: Pandas (Python Package), NumPy, Data Analysis, Data Science, Python Programming, Data Structures, Exploratory Data Analysis, Data Manipulation, Computer Programming\nrating: 4.5\nrating_source: user_reviews\nnum_reviews: 385\nnum_enrolled: 0\nprice_normalized: \nis_free: False\ninstructor_name: \ninstructor_org: Coursera\nimage_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/a3/b4bf1c1b574171b82d7bd553043854/python-101.png?auto=format%2C%20compress%2C%20enhance&dpr=1&w=320&h=180&q=50&fit=crop\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: data-science\nsubcategory: \nhas_certificate: True\nengagement_proxy: 57.37\ncompleteness_score: 0.6667\ntitle_length: 40\ndescription_length: 184\nscraped_at: 2026-04-14T22:20:46.208342+00:00\nbronze_ingested_at: 2026-04-14T22:14:52.089201+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00"),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 7}, page_content='course_sk: 14131\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/math/grade-4-math-tx/x5ff7ebd8e2c0fc69:applying-all-operations\ncanonical_url: https://www.khanacademy.org/math/grade-4-math-tx/x5ff7ebd8e2c0fc69:applying-all-operations\nrow_hash: 20acbca9096092326f283f9656d80f411cf7eeba1215220a4f041a63c26626f8\ntitle: Applying all operations\nheadline: Applying all operations\ndescription: Applying all operations. Provider: Khan Academy. Category: Math.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Math\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 23\ndescription_length: 64\nscraped_at: 2026-04-14T22:37:51.401949+00:00\nbronze_ingested_at: 2026-04-14T22:37:36.68496+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 8}, page_content='course_sk: 15235\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/math/math2/xe2ae2386aa2e13d6:prob\ncanonical_url: https://www.khanacademy.org/math/math2/xe2ae2386aa2e13d6:prob\nrow_hash: 5a7cb796ac6600f79aaced2eaa38e04bc6ede85b076a792a58f19011af334da0\ntitle: Probability\nheadline: Probability\ndescription: Probability. Provider: Khan Academy. Category: Math.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Math\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 11\ndescription_length: 52\nscraped_at: 2026-04-14T22:37:51.341266+00:00\nbronze_ingested_at: 2026-04-14T22:37:36.68496+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 9}, page_content='course_sk: 14117\nsource: khan_academy\nsource_course_key: khan_academy||https://www.khanacademy.org/math/get-ready-for-4th-grade/xe731db3f95b84f06:get-ready-for-fractions\ncanonical_url: https://www.khanacademy.org/math/get-ready-for-4th-grade/xe731db3f95b84f06:get-ready-for-fractions\nrow_hash: 3069aa60b1433f44938f51121242cdf630bf419bcf24a89b484d2ba783d3f6dc\ntitle: Get ready for fractions\nheadline: Get ready for fractions\ndescription: Get ready for fractions. Provider: Khan Academy. Category: Math.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: 0.0\nis_free: True\ninstructor_name: Khan Academy\ninstructor_org: \nimage_url: \nduration_hours: 0.0\nlevel_normalized: All Levels\nlanguage_normalized: English\ncategory: Math\nsubcategory: \nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8\ntitle_length: 23\ndescription_length: 64\nscraped_at: 2026-04-14T22:37:51.38668+00:00\nbronze_ingested_at: 2026-04-14T22:37:36.68496+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 10}, page_content="course_sk: 13629\nsource: coursera\nsource_course_key: coursera||https://www.coursera.org/learn/pearson-data-science-fundamentals-part-2-complete-video-course-machine-lea-0kay6\ncanonical_url: https://www.coursera.org/learn/pearson-data-science-fundamentals-part-2-complete-video-course-machine-lea-0kay6\nrow_hash: ae7c7cbf11083b6046fee3c9a2ec8047df96ffd82662bfbdbd06a2429cea7288\ntitle: Data Science Fundamentals Part 2: Unit 1\nheadline: Skills you'll gain : Exploratory Data Analysis, Matplotlib, Box Plots, Data Analysis, Data Visualization, Descriptive Statistics, Scatter Plots, Data Visualization Software, Histogram, Seaborn, Statistical Analysis, Correlation Analysis, St\ndescription: Skills you'll gain : Exploratory Data Analysis, Matplotlib, Box Plots, Data Analysis, Data Visualization, Descriptive Statistics, Scatter Plots, Data Visualization Software, Histogram, Seaborn, Statistical Analysis, Correlation Analysis, Statistical Methods\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: \nis_free: True\ninstructor_name: \ninstructor_org: Pearson\nimage_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/70/a02950707e4a289b70663621a3a1e3/CSRA_CVR_12.jpg?auto=format%2C%20compress%2C%20enhance&dpr=1&w=320&h=180&fit=crop&q=50\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: data-science\nsubcategory: \nhas_certificate: True\nengagement_proxy: 0.0\ncompleteness_score: 0.6667\ntitle_length: 40\ndescription_length: 257\nscraped_at: 2026-04-14T22:19:05.000209+00:00\nbronze_ingested_at: 2026-04-14T22:14:52.089201+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00"),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 11}, page_content='course_sk: 13652\nsource: coursera\nsource_course_key: coursera||https://www.coursera.org/learn/introduction-to-nosql-databases\ncanonical_url: https://www.coursera.org/learn/introduction-to-nosql-databases\nrow_hash: c001c448e35144cf2cc86dced11a2db61a7a99f3a7bf6546a24558c460c6903c\ntitle: Introduction to NoSQL Databases\nheadline: Introduction to NoSQL Databases\ndescription: Introduction to NoSQL Databases. Provider: IBM. Category: information-technology.\nrating: 4.6\nrating_source: user_reviews\nnum_reviews: 380\nnum_enrolled: 0\nprice_normalized: \nis_free: True\ninstructor_name: \ninstructor_org: IBM\nimage_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/4d/e41c7d06084588a68d754b85f4b088/NoSQL-800x800_square.png?auto=format%2C%20compress%2C%20enhance&dpr=1&w=320&h=180&fit=crop&q=50\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: information-technology\nsubcategory: \nhas_certificate: True\nengagement_proxy: 58.01\ncompleteness_score: 0.6667\ntitle_length: 31\ndescription_length: 81\nscraped_at: 2026-04-14T22:31:38.003169+00:00\nbronze_ingested_at: 2026-04-14T22:29:17.052634+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00'),
 Document(metadata={'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv', 'row': 12}, page_content="course_sk: 13921\nsource: coursera\nsource_course_key: coursera||https://www.coursera.org/learn/information-theory-and-games\ncanonical_url: https://www.coursera.org/learn/information-theory-and-games\nrow_hash: 5acc1dafc523d5f54f6bf8e7ab045f9090ae84dde07682842d105a0b50e7e50c\ntitle: Data Science Decisions in Time: Information Theory & Games\nheadline: Skills you'll gain : Game Theory, Data-Driven Decision-Making, Cybersecurity, Data Science, Algorithms, Reinforcement Learning, AI Security, Machine Learning\ndescription: Skills you'll gain : Game Theory, Data-Driven Decision-Making, Cybersecurity, Data Science, Algorithms, Reinforcement Learning, AI Security, Machine Learning\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nprice_normalized: \nis_free: True\ninstructor_name: \ninstructor_org: Johns Hopkins University\nimage_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/3f/8d055deb7849d5831aca3eb3a283b2/Placeholder_Making_Decisions_in_Time.png?auto=format%2C%20compress%2C%20enhance&dpr=1&w=320&h=180&q=50&fit=crop\nduration_hours: 0.0\nlevel_normalized: Intermediate\nlanguage_normalized: English\ncategory: data-science\nsubcategory: \nhas_certificate: True\nengagement_proxy: 0.0\ncompleteness_score: 0.6667\ntitle_length: 58\ndescription_length: 157\nscraped_at: 2026-04-14T22:19:05.077034+00:00\nbronze_ingested_at: 2026-04-14T22:14:52.089201+00:00\nloaded_at: 2026-03-19T14:47:57.90376+00:00\nupdated_at: 2026-04-14T22:42:33.120104+00:00"),

In [1]:
import pandas as pd
df = pd.read_csv("C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_raw.csv")

In [3]:
df

,course_sk,source,source_course_key,canonical_url,row_hash,title,headline,description,rating,rating_source,...,subcategory,has_certificate,engagement_proxy,completeness_score,title_length,description_length,scraped_at,bronze_ingested_at,loaded_at,updated_at
0,14099,khan_academy,khan_academy||https://www.khanacademy.org/econ...,https://www.khanacademy.org/economics-finance-...,7bc951928f6df514f133bea671f18464e37c649cc4e4e8...,Economic stabilization,Economic stabilization,Economic stabilization. Provider: Khan Academy...,0.0,unavailable,...,NaN,False,0.00,0.8000,22,78,2026-04-14T21:41:44.487823+00:00,2026-04-14T21:41:26.92703+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
1,12754,coursera,coursera||https://www.coursera.org/learn/objec...,https://www.coursera.org/learn/object-oriented...,92687299a663f87f7d35d6d476c6634b339f2c0849beba...,Object-Oriented Programming and GUI with Python,Skills you'll gain : Object Oriented Programmi...,Skills you'll gain : Object Oriented Programmi...,3.7,user_reviews,...,NaN,True,38.20,0.6667,47,237,2026-04-14T22:26:57.389543+00:00,2026-04-14T22:21:51.370539+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
2,14102,khan_academy,khan_academy||https://www.khanacademy.org/math...,https://www.khanacademy.org/math/6th-grade-mat...,a627ae395488b1fc03548af919933cd44af443c1086f86...,6th grade (Eureka Math Squared-aligned),6th grade (Eureka Math Squared-aligned),6th grade (Eureka Math Squared-aligned). Provi...,0.0,unavailable,...,NaN,False,0.00,0.8000,39,80,2026-04-14T22:37:51.405454+00:00,2026-04-14T22:37:36.68496+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
3,14103,khan_academy,khan_academy||https://www.khanacademy.org/math...,https://www.khanacademy.org/math/algebra-1-ny-...,1d9129f9f96c50923f0ba867cb7084bb9ca28945812762...,Absolute value & piecewise functions,Absolute value & piecewise functions,Absolute value & piecewise functions. Provider...,0.0,unavailable,...,NaN,False,0.00,0.8000,36,77,2026-04-14T22:37:51.408885+00:00,2026-04-14T22:37:36.68496+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
4,12970,coursera,coursera||https://www.coursera.org/degrees/mas...,https://www.coursera.org/degrees/master-of-com...,3ecfd83bc3d1264bf295d289b075d07c71b2b21de3bf8e...,Master of Computer Science (feat. Data Science...,Degree · 12 – 36 months,Degree · 12 – 36 months,0.0,unavailable,...,NaN,True,0.00,0.6667,53,23,2026-04-14T22:17:41.629568+00:00,2026-04-14T22:14:52.089201+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7444,26756,youtube,youtube||https://www.youtube.com/watch?v=lk_SZ...,https://www.youtube.com/watch?v=lk_SZHnUPbE,4c7842fdfb7583cd823ead36d0bb610587847d6e3ba886...,Introduction to Computer | Computer Fundamenta...,Pathshala IT Academy,Pathshala Classes is one of the best education...,5.0,user_reviews,...,NaN,False,79.03,0.8667,91,2646,2026-04-14T17:44:26.354526+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7445,26757,youtube,youtube||https://www.youtube.com/watch?v=sw3AL...,https://www.youtube.com/watch?v=sw3ALlNMz4A,504089f927327e121d61f4d502c7728f9819cd75ae9c12...,"Strings Indexing, Slicing and Methods | Python...",Rishabh Mishra,"Strings Indexing, Slicing and Methods in Pytho...",2.9,user_reviews,...,NaN,False,71.32,0.8667,67,1513,2026-04-14T17:44:26.190795+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7446,26758,youtube,youtube||https://www.youtube.com/watch?v=JTtgb...,https://www.youtube.com/watch?v=JTtgb6SSRWA,5298488cb03ef92f93fbfcd12ed1b91c60d290ec914f13...,Class 11 CS/IP Top 20 Most Important Python Pr...,Barkha Mam - App Tech Guru,Class 11 CS/IP Top 20 Most Important Python Pr...,3.0,user_reviews,...,NaN,False,74.13,0.8667,97,1928,2026-04-14T17:38:36.726137+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7447,26759,youtube,youtube||https://www.youtube.com/playlist?list...,https://www.youtube.com/playlist?list=PLKKfKV1...,b4edb9186765d0f327e691ea7d197d9d783aed58921e89...,Python for Class 12,Apni Kaksha Official,Apni Kaksha Official. Provider: Apni Kaksha Of...,0.0,unavailable,...,NaN,False,0.00,0.8000,19,83,2026-04-14T17:37:16.584884+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7448,26760,youtube,youtube||https://www.youtube.com/playlist?list...,https://www.youtube.com/playlist?list=PLezlYAh...,f9f06f46907972bd7093722f40fa443d290ad541695e3d...,Python Coding Tutorial for Kids in Hindi,Learn With Fun,Learn With Fun. Provider: Learn With Fun. Cate...,0.0,unavailable,...,NaN,False,0.00,0.8000,40,71,2026-04-14T17:36:14.045614+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00

In [4]:
df.isna().sum()

course_sk                 0
source                    0
source_course_key         0
canonical_url             0
row_hash                  0
title                     0
headline                  0
description              18
rating                    0
rating_source             0
num_reviews               0
num_enrolled              0
price_normalized       3438
is_free                   0
instructor_name        1360
instructor_org         4136
image_url              1720
duration_hours            0
level_normalized          0
language_normalized       0
category                  0
subcategory            7350
has_certificate           0
engagement_proxy          0
completeness_score        0
title_length              0
description_length        0
scraped_at                0
bronze_ingested_at        0
loaded_at                 0
updated_at                0
dtype: int64

In [5]:
df.drop(columns=["price_normalized","instructor_name","instructor_org","image_url","subcategory"], inplace=True)

In [6]:
df

,course_sk,source,source_course_key,canonical_url,row_hash,title,headline,description,rating,rating_source,...,category,has_certificate,engagement_proxy,completeness_score,title_length,description_length,scraped_at,bronze_ingested_at,loaded_at,updated_at
0,14099,khan_academy,khan_academy||https://www.khanacademy.org/econ...,https://www.khanacademy.org/economics-finance-...,7bc951928f6df514f133bea671f18464e37c649cc4e4e8...,Economic stabilization,Economic stabilization,Economic stabilization. Provider: Khan Academy...,0.0,unavailable,...,Economics & Finance,False,0.00,0.8000,22,78,2026-04-14T21:41:44.487823+00:00,2026-04-14T21:41:26.92703+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
1,12754,coursera,coursera||https://www.coursera.org/learn/objec...,https://www.coursera.org/learn/object-oriented...,92687299a663f87f7d35d6d476c6634b339f2c0849beba...,Object-Oriented Programming and GUI with Python,Skills you'll gain : Object Oriented Programmi...,Skills you'll gain : Object Oriented Programmi...,3.7,user_reviews,...,computer-science,True,38.20,0.6667,47,237,2026-04-14T22:26:57.389543+00:00,2026-04-14T22:21:51.370539+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
2,14102,khan_academy,khan_academy||https://www.khanacademy.org/math...,https://www.khanacademy.org/math/6th-grade-mat...,a627ae395488b1fc03548af919933cd44af443c1086f86...,6th grade (Eureka Math Squared-aligned),6th grade (Eureka Math Squared-aligned),6th grade (Eureka Math Squared-aligned). Provi...,0.0,unavailable,...,Math,False,0.00,0.8000,39,80,2026-04-14T22:37:51.405454+00:00,2026-04-14T22:37:36.68496+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
3,14103,khan_academy,khan_academy||https://www.khanacademy.org/math...,https://www.khanacademy.org/math/algebra-1-ny-...,1d9129f9f96c50923f0ba867cb7084bb9ca28945812762...,Absolute value & piecewise functions,Absolute value & piecewise functions,Absolute value & piecewise functions. Provider...,0.0,unavailable,...,Math,False,0.00,0.8000,36,77,2026-04-14T22:37:51.408885+00:00,2026-04-14T22:37:36.68496+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
4,12970,coursera,coursera||https://www.coursera.org/degrees/mas...,https://www.coursera.org/degrees/master-of-com...,3ecfd83bc3d1264bf295d289b075d07c71b2b21de3bf8e...,Master of Computer Science (feat. Data Science...,Degree · 12 – 36 months,Degree · 12 – 36 months,0.0,unavailable,...,data-science,True,0.00,0.6667,53,23,2026-04-14T22:17:41.629568+00:00,2026-04-14T22:14:52.089201+00:00,2026-03-19T14:47:57.90376+00:00,2026-04-14T22:42:33.120104+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7444,26756,youtube,youtube||https://www.youtube.com/watch?v=lk_SZ...,https://www.youtube.com/watch?v=lk_SZHnUPbE,4c7842fdfb7583cd823ead36d0bb610587847d6e3ba886...,Introduction to Computer | Computer Fundamenta...,Pathshala IT Academy,Pathshala Classes is one of the best education...,5.0,user_reviews,...,Python Programming,False,79.03,0.8667,91,2646,2026-04-14T17:44:26.354526+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7445,26757,youtube,youtube||https://www.youtube.com/watch?v=sw3AL...,https://www.youtube.com/watch?v=sw3ALlNMz4A,504089f927327e121d61f4d502c7728f9819cd75ae9c12...,"Strings Indexing, Slicing and Methods | Python...",Rishabh Mishra,"Strings Indexing, Slicing and Methods in Pytho...",2.9,user_reviews,...,Python Programming,False,71.32,0.8667,67,1513,2026-04-14T17:44:26.190795+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7446,26758,youtube,youtube||https://www.youtube.com/watch?v=JTtgb...,https://www.youtube.com/watch?v=JTtgb6SSRWA,5298488cb03ef92f93fbfcd12ed1b91c60d290ec914f13...,Class 11 CS/IP Top 20 Most Important Python Pr...,Barkha Mam - App Tech Guru,Class 11 CS/IP Top 20 Most Important Python Pr...,3.0,user_reviews,...,Python Programming,False,74.13,0.8667,97,1928,2026-04-14T17:38:36.726137+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7447,26759,youtube,youtube||https://www.youtube.com/playlist?list...,https://www.youtube.com/playlist?list=PLKKfKV1...,b4edb9186765d0f327e691ea7d197d9d783aed58921e89...,Python for Class 12,Apni Kaksha Official,Apni Kaksha Official. Provider: Apni Kaksha Of...,0.0,unavailable,...,Python Programming,False,0.00,0.8000,19,83,2026-04-14T17:37:16.584884+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00
7448,26760,youtube,youtube||https://www.youtube.com/playlist?list...,https://www.youtube.com/playlist?list=PLezlYAh...,f9f06f46907972bd7093722f40fa443d290ad541695e3d...,Python Coding Tutorial for Kids in Hindi,Learn With Fun,Learn With Fun. Provider: Learn With Fun. Cate...,0.0,unavailable,...,Python Programming,False,0.00,0.8000,40,71,2026-04-14T17:36:14.045614+00:00,2026-04-14T17:34:54.779169+00:00,2026-04-14T22:42:33.120104+00:00,2026-04-14T22:42:33.120104+00:00

In [7]:
df.dropna(inplace=True)

In [8]:
df.isna().sum()

course_sk              0
source                 0
source_course_key      0
canonical_url          0
row_hash               0
title                  0
headline               0
description            0
rating                 0
rating_source          0
num_reviews            0
num_enrolled           0
is_free                0
duration_hours         0
level_normalized       0
language_normalized    0
category               0
has_certificate        0
engagement_proxy       0
completeness_score     0
title_length           0
description_length     0
scraped_at             0
bronze_ingested_at     0
loaded_at              0
updated_at             0
dtype: int64

In [9]:
df.drop(columns=["updated_at","loaded_at","bronze_ingested_at","scraped_at"], inplace=True)

In [12]:
df["title_length"]

0       22
1       47
2       39
3       36
4       53
        ..
7444    91
7445    67
7446    97
7447    19
7448    40
Name: title_length, Length: 7431, dtype: int64

In [13]:
df.drop(columns = ["description_length","title_length"], inplace=True)

In [15]:
df.head()

,course_sk,source,source_course_key,canonical_url,row_hash,title,headline,description,rating,rating_source,num_reviews,num_enrolled,is_free,duration_hours,level_normalized,language_normalized,category,has_certificate,engagement_proxy,completeness_score
0,14099,khan_academy,khan_academy||https://www.khanacademy.org/econ...,https://www.khanacademy.org/economics-finance-...,7bc951928f6df514f133bea671f18464e37c649cc4e4e8...,Economic stabilization,Economic stabilization,Economic stabilization. Provider: Khan Academy...,0.0,unavailable,0,0,True,0.0,All Levels,English,Economics & Finance,False,0.0,0.8000
1,12754,coursera,coursera||https://www.coursera.org/learn/objec...,https://www.coursera.org/learn/object-oriented...,92687299a663f87f7d35d6d476c6634b339f2c0849beba...,Object-Oriented Programming and GUI with Python,Skills you'll gain : Object Oriented Programmi...,Skills you'll gain : Object Oriented Programmi...,3.7,user_reviews,16,0,True,0.0,Beginner,English,computer-science,True,38.2,0.6667
2,14102,khan_academy,khan_academy||https://www.khanacademy.org/math...,https://www.khanacademy.org/math/6th-grade-mat...,a627ae395488b1fc03548af919933cd44af443c1086f86...,6th grade (Eureka Math Squared-aligned),6th grade (Eureka Math Squared-aligned),6th grade (Eureka Math Squared-aligned). Provi...,0.0,unavailable,0,0,True,0.0,All Levels,English,Math,False,0.0,0.8000
3,14103,khan_academy,khan_academy||https://www.khanacademy.org/math...,https://www.khanacademy.org/math/algebra-1-ny-...,1d9129f9f96c50923f0ba867cb7084bb9ca28945812762...,Absolute value & piecewise functions,Absolute value & piecewise functions,Absolute value & piecewise functions. Provider...,0.0,unavailable,0,0,True,0.0,All Levels,English,Math,False,0.0,0.8000
4,12970,coursera,coursera||https://www.coursera.org/degrees/mas...,https://www.coursera.org/degrees/master-of-com...,3ecfd83bc3d1264bf295d289b075d07c71b2b21de3bf8e...,Master of Computer Science (feat. Data Science...,Degree · 12 – 36 months,Degree · 12 – 36 months,0.0,unavailable,0,0,False,0.0,Unknown,English,data-science,True,0.0,0.6667

In [1]:
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer

from qdrant_client import QdrantClient
from qdrant_client.http.models import VectorParams, Distance, Batch, Filter, MatchValue, FieldCondition

c:\Users\youssef gerges\anaconda3\envs\Project\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Load dotenv file
_ = load_dotenv(override=True)
qdrant_key = os.getenv('QDRANT_API_KEY')
qdrant_url = os.getenv('QDRANT_URL')

In [3]:
client = QdrantClient(url=qdrant_url, api_key=qdrant_key)

C:\Users\youssef gerges\AppData\Local\Temp\ipykernel_6404\2775912269.py:1: UserWarning: Qdrant client version 1.15.0 is incompatible with server version 1.17.1. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  client = QdrantClient(url=qdrant_url, api_key=qdrant_key)

In [4]:
from sentence_transformers import SentenceTransformer
model_hugging_6 = SentenceTransformer(model_name_or_path='all-MiniLM-L6-v2', device='cpu')

In [7]:
query_vector = model_hugging_6.encode(["Machine learning"]) # Just to check if it's working, should print the first 5 values of the embedding vector for "Hello world!"

In [9]:
len(query_vector[0])

384

In [6]:
len(model_hugging_6.encode(["Machine learning"])[0])

384

In [11]:
client.search(collection_name="Graduation_Project_Collection", query_vector=query_vector[0], limit=5)

C:\Users\youssef gerges\AppData\Local\Temp\ipykernel_6404\2553695260.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  client.search(collection_name="Graduation_Project_Collection", query_vector=query_vector[0], limit=5)

[ScoredPoint(id='1516717e-3d3a-4d85-890b-737a144a6ae7', version=131, score=0.48992744, payload={'text': 'course_sk: 25870\nsource: youtube\nsource_course_key: youtube||https://www.youtube.com/playlist?list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw\ncanonical_url: https://www.youtube.com/playlist?list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw\nrow_hash: e75f441f93dccb6df575be5dc2064dd6e6dcebe8a38f312ba19ecb626c4c4b17\ntitle: Machine Learning Tutorial Python | Machine Learning For Beginners\nheadline: codebasics\ndescription: In this video series, we are going to learn about machine learning with Python. There are activities where computers are better than humans, and some activities where humans are better than computers. In simple words, machine learning is the technique that makes computers better at things than humans. It’s about making machines learn the things humans do. Machine learning is a bigger area, of which deep learning and mathematical models are important parts. One might think about why it is important to learn machine learning? It is because it has a big implication in real life too. Spam filtering in emails, voice assistance devices, online video or music streaming recommendations, are a few of the real-life applications of machine learning which are already available to us. However, the best use of this feature can be expected in the near-decade in the form of driverless cars. Go through this machine learning playlist to understand these concepts more easily. This machine learning tutorials playlist includes linear regression, gradient descent, logistic regression, decision tree, support vector, K-fold cross-validation, KNN classification, etc. The playlist also includes several practical implication projects which will help you get a more clear understanding of the concept. Another topic included in this machine learning course is Feature Engineering, which is an important part of data analytics and machine learning.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nis_free: True\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: Python Programming\nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8', 'metadata': {'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_cleaned.csv', 'row': 6548}}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id='ee3326ca-a9d5-4e39-bda2-6f54402ff3cd', version=136, score=0.4571697, payload={'text': 'course_sk: 26118\nsource: youtube\nsource_course_key: youtube||https://www.youtube.com/playlist?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH\ncanonical_url: https://www.youtube.com/playlist?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH\nrow_hash: 89f8a1694a2c6f0cc162a8ff517b499a2a5884298b158d090055393f1b033527\ntitle: 100 Days of Machine Learning | CampusX\nheadline: CampusX\ndescription: Welcome to the 100 Days of Machine Learning series — one of the most watched and most trusted and Evergreen Machine Learning playlists on Indian YouTube, followed by millions of learners who want to build a strong foundation in ML. This playlist is designed as a step-by-step roadmap to master Machine Learning, starting from the absolute basics and gradually moving toward advanced concepts and real-world implementation. Instead of jumping directly into code, the series focuses on building clear intuition, strong fundamentals, and practical understanding of how machine learning actually works. What you will learn in this series: • AI vs Machine Learning vs Deep Learning • Types of Machine Learning (Supervised, Unsupervised, Reinforcement Learning) • Data preprocessing and feature engineering • Exploratory Data Analysis (EDA) • Important ML algorithms (Regression, Classification, Clustering, etc.) • Model evaluation and validation techniques • Real-world ML workflow and best practices Each video covers a specific concept in a simple and structured way so you can build knowledge one step at a time, just like a 100-day learning roadmap. If you want to build a strong Machine Learning foundation for Data Science, AI, or ML Engineering, this playlist will guide you from beginner concepts to industry-level understanding. Notes: https://learnwith.campusx.in/s/store/courses/YouTube%20Notes\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nis_free: True\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: Python Programming\nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.9333', 'metadata': {'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_cleaned.csv', 'row': 6792}}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id='3e27d585-94f9-4006-850c-dc5474f87be6', version=99, score=0.45289668, payload={'text': 'course_sk: 17427\nsource: udemy\nsource_course_key: udemy||https://www.udemy.com/course/machine-learning-for-absolute-beginners-level-1\ncanonical_url: https://www.udemy.com/course/machine-learning-for-absolute-beginners-level-1\nrow_hash: 416cfc6656475eb80f081e32b648af7d233599068f1105a79f27b0eb324467e0\ntitle: Machine Learning for Absolute Beginners - Level 1\nheadline: Learn the Fundamental Concepts of Artificial Intelligence and Machine Learning as the Next Game-Changing Technology\ndescription: Learn the Fundamental Concepts of Artificial Intelligence and Machine Learning as the Next Game-Changing Technology\nrating: 4.5\nrating_source: user_reviews\nnum_reviews: 34029\nnum_enrolled: 0\nis_free: False\nduration_hours: 4.5\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: development\nhas_certificate: False\nengagement_proxy: 61.5\ncompleteness_score: 0.7333', 'metadata': {'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_cleaned.csv', 'row': 4921}}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id='12c30be4-ffa6-4f76-af04-9bc18a90d084', version=131, score=0.44990197, payload={'text': "course_sk: 25821\nsource: youtube\nsource_course_key: youtube||https://www.youtube.com/watch?v=hDKCxebp88A\ncanonical_url: https://www.youtube.com/watch?v=hDKCxebp88A\nrow_hash: c2d2d1a0a7b8b6f6c976068b1ca99869960ab956ae17600912fc44af53d91dd6\ntitle: Machine Learning with Python and Scikit-Learn – Full Course\nheadline: freeCodeCamp.org\ndescription: This course is a practical and hands-on introduction to Machine Learning with Python and Scikit-Learn for beginners with basic knowledge of Python and statistics. It is designed and taught by Aakash N S, CEO and co-founder of Jovian. Check out their YouTube channel here: https://youtube.com/@jovianhq We'll start with the basics of machine learning by exploring models like linear & logistic regression and then move on to tree-based models like decision trees, random forests, and gradient-boosting machines. We'll also discuss best practices for approaching and managing machine learning projects and build a state-of-the-art machine learning model for a real-world dataset from scratch. We'll also look at unsupervised learning & recommendations briefly and walk through the process of deploying a machine-learning model to the cloud using the Flask web framework. By the end of this course, you'll be able to confidently build, train, and deploy machine learning models in the real world. To get the most out of this course, follow along & type out all the code yourself, and apply the techniques covered here to other real-world datasets & competitions that you can find on platforms like Kaggle. ❤️ Try interactive Python courses we love, right in your browser: https://scrimba.com/freeCodeCamp-Python (Made possible by a grant from our friends at Scrimba) ⭐️ Topics & Notebooks ⭐️ ⌨️ (00:00:00) Introduction ⌨️ (00:00:25) Lesson 1 - Linear Regression and Gradient Descent 🔗 https://jovian.ai/aakashns/python-sklearn-linear-regression ⌨️ (02:17:30) Lesson 2 - Logistic Regression for Classification 🔗 https://jovian.ai/aakashns/python-sklearn-logistic-regression ⌨️ (04:53:26) Lesson 3 - Decision Trees and Random Forests 🔗 https://jovian.ai/aakashns/sklearn-decision-trees-random-forests ⌨️ (07:25:29) Lesson 4 - How to Approach Machine Learning Projects 🔗 https://jovian.com/aakashns/how-to-approach-ml-problems ⌨️ (10:06:13) Lesson 5 - Gradient Boosting Machines with XGBoost 🔗 https://jovian.ai/aakashns/python-gradient-boosting-machines ⌨️ (12:20:57) Lesson 6 - Unsupervised Learning using Scikit-Learn 🔗 https://jovian.ai/aakashns/sklearn-unsupervised-learning , https://jovian.ai/aakashns/movielens-fastai ⌨️ (13:53:18) Lesson 7 - Machine Learning Project from Scratch 🔗 https://jovian.com/aakashns/nyc-taxi-fare-prediction-filled , https://jovian.com/aakashns/nyc-taxi-fare-prediction-blank ⌨️ (16:45:47) Lesson 8 - Deploying a Machine Learning Project with Flask 🔗 https://jovian.com/biraj/deploying-a-machine-learning-model 🎉 Thanks to our Champion and Sponsor supporters: 👾 davthecoder 👾 jedi-or-sith 👾 南宮千影 👾 Agustín Kussrow 👾 Nattira Maneerat 👾 Heather Wcislo 👾 Serhiy Kalinets 👾 Justin Hual 👾 Otis Morgan 👾 Oscar Rahnama -- Learn to code for free and get a developer job: https://www.freecodecamp.org Read hundreds of articles on programming: https://freecodecamp.org/news\nrating: 2.8\nrating_source: user_reviews\nnum_reviews: 771\nnum_enrolled: 988122\nis_free: True\nduration_hours: 18.01\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: Python Programming\nhas_certificate: False\nengagement_proxy: 83.48\ncompleteness_score: 0.8", 'metadata': {'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_cleaned.csv', 'row': 6500}}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id='2e99ea5c-906c-4b58-abe3-4630d6878e8e', version=131, score=0.445875, payload={'text': 'course_sk: 25826\nsource: youtube\nsource_course_key: youtube||https://www.youtube.com/playlist?list=PLaldQ9PzZd9qT0KsKJ7yCq70iFFP3MFJ5\ncanonical_url: https://www.youtube.com/playlist?list=PLaldQ9PzZd9qT0KsKJ7yCq70iFFP3MFJ5\nrow_hash: 8a57a145c5d776e168343475400b4b08698fe2b955f1fa96e4fc06190e89458b\ntitle: Complete Machine Learning Course with Projects | Learn ML Step-by-Step\nheadline: Sheryians AI School\ndescription: Welcome to the Complete Machine Learning Course, your one-stop destination to master machine learning from the ground up. This playlist is designed for beginners, students, and aspiring data scientists who want to learn ML through a structured, project-based, and hands-on approach. We’ll cover everything from the basics of machine learning to advanced concepts, including: Supervised Learning (Regression & Classification) Unsupervised Learning (Clustering, Dimensionality Reduction) Model Evaluation Techniques Feature Engineering & Selection Real-World Projects with Python and Scikit-learn Interview-ready concepts and visual explanations Each video is packed with clear intuition, theory, coding examples, and practical tips to help you become a confident ML practitioner. 📌 Prerequisites: To get the most out of this course, you should be familiar with: Basic Python programming (variables, loops, functions) Elementary statistics (mean, median, standard deviation) High school-level mathematics (algebra, basic linear equations) If you’re new to Python or statistics, don’t worry — the videos are explained in a beginner-friendly way, and you’ll be able to catch up as we go. 👉 Need a refresher? Check out our Data Science Playlist, where we cover Python, statistics, and all the foundational concepts you’ll need before diving into machine learning.\nrating: 0.0\nrating_source: unavailable\nnum_reviews: 0\nnum_enrolled: 0\nis_free: True\nduration_hours: 0.0\nlevel_normalized: Beginner\nlanguage_normalized: English\ncategory: Python Programming\nhas_certificate: False\nengagement_proxy: 0.0\ncompleteness_score: 0.8', 'metadata': {'source': 'C:\\AI\\Rag Pipline Graduation Project\\src\\data\\graduation_data_cleaned.csv', 'row': 6505}}, vector=None, shard_key=None, order_value=None)]

In [15]:
from openai import OpenAI

client = OpenAI(
    base_url="https://deceased-backstab-hydroxide.ngrok-free.dev/v1", 
    api_key="ollama" 
)

response = client.chat.completions.create(
  model="qwen3.5:latest", 
  messages=[
    {"role": "user", "content": "مرحباً، كيف حالك؟"}
  ]
)

print(response.choices[0].message.content)

مرحباً! أنا بخير، شكرًا لسؤالك. كيف يمكنني مساعدتك اليوم؟ 😊

In [2]:
text = "i want to learn machine learning provide top 10 subjects to learn in machine learning"
text[:40000].strip()

'i want to learn machine learning provide top 10 subjects to learn in machine learning'

In [5]:
import json

json_answers =  {
  "signal": "ResponseSignal.FINAL_ANSWER_SUCCESS.value",
  "results": [
    {
      "topic": "1.  Programming Languages (Python, SQL)",
      "answer": "{\n  \"message\": \"Here are the courses related to Python and SQL programming languages that I found in the documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Python Programming Course For Begginers || Python 101\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/watch?v=fMWF7NF_ZZc\",\n      \"rating\": 1.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 14,\n      \"num_enrolled\": 3225,\n      \"is_free\": true,\n      \"duration_hours\": 8.89,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 58.66,\n      \"completeness_score\": 0.8667\n    },\n    {\n      \"title\": \"Day 1 : Basics of Programming | Python Course in Telugu | Vamsi Bhavani\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/watch?v=n0zEsDkwwQs\",\n      \"rating\": 4.0,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 403,\n      \"num_enrolled\": 511135,\n      \"is_free\": true,\n      \"duration_hours\": 0.38,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"Te\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 89.06,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"Databases and SQL for Data Science with Python\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/sql-data-science\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 23000,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"data-science\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 62.9,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Python Programming Tutorial 🔥 Full Python Course for Beginners\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLwhVruPHD9rzDSsfS5ZKXrUPAo6I7RQEh\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"Python Language in Pashto For Beginners by Hassan\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLDdMcjWqAKJEY176iqh-QOjouaCItHZIh\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.8\n    }\n  ]\n}"
    },
    {
      "topic": "2.  Database Management (Relational & NoSQL)",
      "answer": "{\n  \"message\": \"Here are the courses related to Database Management, including both Relational and NoSQL databases, that I found in the provided documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Introduction to NoSQL Databases\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/introduction-to-nosql-databases\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 380,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"information-technology\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 58.01,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"The Firebase Database For SQL Developers\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLl-K7zZEsYLlP-k-RKFa7RyNPa9_wCH2s\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"SQL & Databases\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.8\n    },\n    {\n      \"title\": \"Database Management Systems (DBMS)\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLBlnK6fEyqRiyryTrbKHX1Sh9luYI0dhX\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"SQL & Databases\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"Fundamentals of Database Engineering\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/database-engines-crash-course\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 11788,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 31.0,\n      \"level_normalized\": \"Intermediate\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.9,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Database Management System from scratch - Part 1\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/database-management-systems\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 6434,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 12.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    },
    {
      "topic": "3.  Data Warehousing & Data Modeling",
      "answer": "{\n  \"message\": \"Here are some courses related to Data Warehousing and Data Modeling that I found for you:\",\n  \"courses\": [\n    {\n      \"title\": \"Data Warehouse - The Ultimate Guide\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/data-warehouse-the-ultimate-guide\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 12532,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 9.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.8\n    },\n    {\n      \"title\": \"Data Warehousing and Business Intelligence\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/data-warehousing-business-intelligence\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 129,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 53.34,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Data Warehousing for Business Intelligence\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/specializations/data-warehousing\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 4100,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Advanced\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 61.5,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Business intelligence and data warehousing\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/business-intelligence-data-warehousing\",\n      \"rating\": 3.9,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 102,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Intermediate\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 47.43,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Data Warehouse Fundamentals for Beginners\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/data-warehouse-fundamentals-for-beginners\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 34057,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 5.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    },
    {
      "topic": "4.  Big Data Frameworks (e.g., Apache Spark, Hadoop)",
      "answer": "{\n  \"message\": \"Here are some courses related to Big Data Frameworks like Apache Spark and Hadoop:\",\n  \"courses\": [\n    {\n      \"title\": \"Taming Big Data with Apache Spark 4 and Python - Hands On!\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/taming-big-data-with-apache-spark-hands-on\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 17983,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 9.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Apache Spark with Scala - Hands On with Big Data!\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/apache-spark-with-scala-hands-on-with-big-data\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 18847,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 9.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"The Ultimate Hands-On Hadoop: Tame your Big Data!\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/the-ultimate-hands-on-hadoop-tame-your-big-data\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 31093,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 14.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Big Data Integration and Processing\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/big-data-integration-processing\",\n      \"rating\": 4.4,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 2400,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"data-science\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 60.8,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Introduction to Big Data\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/big-data-introduction\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 11000,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Mixed\",\n      \"language_normalized\": \"English\",\n      \"category\": \"data-science\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.6667\n    }\n  ]\n}"
    },
    {
      "topic": "5.  Cloud Data Platforms (AWS, Azure, GCP services)",
      "answer": "{\n  \"message\": \"Here are the courses related to Cloud Data Platforms, including AWS and GCP services, that I found in the provided documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Google Cloud Platform (GCP) Fundamentals for Beginners\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/google-cloud-platform-gcp-fundamentals-for-beginners\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 49493,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 5.5,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 61.5,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Cloud Computing Applications\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/cloud-applications-part1\",\n      \"rating\": 4.3,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 846,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Intermediate\",\n      \"language_normalized\": \"English\",\n      \"category\": \"information-technology\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 59.38,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Introduction to Cloud Computing on AWS for Beginners [2026]\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/introduction-to-cloud-computing-on-amazon-aws-for-beginners\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 38705,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 10.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"GCP DevOps Full Course\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLdRNkbtVPBrQ3mZBiczkT7PBRJ5Si-JsZ\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"DevOps & CI/CD\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"GCP for Beginners - Become a Google Cloud Digital Leader\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/google-cloud-digital-leader-certification\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 17339,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 12.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.9,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    },
    {
      "topic": "6.  ETL/ELT Pipeline Orchestration (e.g., Apache Airflow)",
      "answer": "{\n  \"message\": \"Here is a course related to ETL/ELT Pipeline Orchestration using Apache Airflow that I found in the documents.\",\n  \"courses\": [\n    {\n      \"title\": \"The Complete Hands-On Introduction to Apache Airflow 3\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 14008,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 4.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    },
    {
      "topic": "7.  Data Streaming Technologies (e.g., Apache Kafka)",
      "answer": "{\n  \"message\": \"Here are some courses related to Data Streaming Technologies, specifically Apache Kafka, found in the provided documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Apache Kafka Series - Kafka Streams for Data Processing\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/kafka-streams\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 6726,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 5.0,\n      \"level_normalized\": \"Intermediate\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 61.5,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Apache Kafka Series - Learn Apache Kafka for Beginners v3\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/apache-kafka\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 52920,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 8.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.8\n    },\n    {\n      \"title\": \"Apache Kafka for absolute beginners\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/apache-kafka-for-beginners\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 7827,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 5.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"The Ultimate Hands-On Hadoop: Tame your Big Data!\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/the-ultimate-hands-on-hadoop-tame-your-big-data\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 31093,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 14.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    },
    {
      "topic": "8.  Data Governance, Quality, and Security",
      "answer": "{\n  \"message\": \"Here are the courses related to Data Governance, Quality, and Security that I found in the provided documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Data Governance - The Complete Course for Beginners\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/data-governance-training-course\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 7893,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 9.5,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"business\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Data Governance Fundamentals\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/data-governance-fundamentals\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 15276,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 1.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 61.5,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"IBM Data Privacy for Information Architecture\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/ibm-data-privacy\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 49,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Mixed\",\n      \"language_normalized\": \"English\",\n      \"category\": \"information-technology\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 48.49,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Data Privacy and Protection Standards\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/data-privacy-and-protection-standards\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 37,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"information-technology\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 48.7,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Information Systems Auditing and Governance\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/packt-information-systems-auditing-and-governance-2vnoc\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 36,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Intermediate\",\n      \"language_normalized\": \"English\",\n      \"category\": \"information-technology\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 47.88,\n      \"completeness_score\": 0.6667\n    }\n  ]\n}"
    },
    {
      "topic": "9.  Version Control & CI/CD Practices",
      "answer": "{\n  \"message\": \"Here are some courses related to Version Control and CI/CD practices that I found in the documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Introduction to Continuous Integration & Continuous Delivery\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/introduction-to-continuous-integration-and-continuous-delivery\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 27971,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 2.5,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 61.5,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"DevOps, CI/CD(Continuous Integration/Delivery) for Beginners\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/ci-cd-devops\",\n      \"rating\": 4.5,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 55408,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 1.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 61.5,\n      \"completeness_score\": 0.8\n    },\n    {\n      \"title\": \"DevOps Full Course for Beginners | CI/CD, Docker, Kubernetes Explained\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PL5VWSIe6Ke7mUacQwr68BbRaKM_ZhkYtt\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"DevOps & CI/CD\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"Git with Azure DevOps & Visual Studio\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLGxFXI4dC2sgDg3UDOatuVquVUXh8EBl7\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"DevOps & CI/CD\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.8\n    },\n    {\n      \"title\": \"GitHub Actions - The Complete Guide\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/github-actions-the-complete-guide\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 11287,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 10.5,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.9,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    },
    {
      "topic": "10. Distributed Systems & System Design Principles",
      "answer": "{\n  \"message\": \"Here are some courses related to Distributed Systems and System Design Principles that I found:\",\n  \"courses\": [\n    {\n      \"title\": \"Software Architecture & Design of Modern Large Scale Systems\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/software-architecture-design-of-modern-large-scale-systems\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 17168,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 8.0,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"development\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.9,\n      \"completeness_score\": 0.7333\n    },\n    {\n      \"title\": \"Design Microservices Architecture with Patterns & Principles\",\n      \"source\": \"udemy\",\n      \"url\": \"https://www.udemy.com/course/design-microservices-architecture-with-patterns-principles\",\n      \"rating\": 4.6,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 7304,\n      \"num_enrolled\": 0,\n      \"is_free\": false,\n      \"duration_hours\": 15.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"it-and-software\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 62.2,\n      \"completeness_score\": 0.7333\n    }\n  ]\n}"
    }
  ]
}

# Parse string into a dictionary
# parsed_data = json.loads(json_string)

# Save to file with formatting (indent=4 makes it readable)
with open("courses_data.json", "w", encoding="utf-8") as f:
    json.dump(json_answers, f, indent=4, ensure_ascii=False)

print("File saved successfully!")

File saved successfully!

In [9]:
import json

json_string = """ {\n  \"message\": \"Here are the courses related to Python and SQL programming languages that I found in the documents.\",\n  \"courses\": [\n    {\n      \"title\": \"Python Programming Course For Begginers || Python 101\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/watch?v=fMWF7NF_ZZc\",\n      \"rating\": 1.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 14,\n      \"num_enrolled\": 3225,\n      \"is_free\": true,\n      \"duration_hours\": 8.89,\n      \"level_normalized\": \"All Levels\",\n      \"language_normalized\": \"English\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 58.66,\n      \"completeness_score\": 0.8667\n    },\n    {\n      \"title\": \"Day 1 : Basics of Programming | Python Course in Telugu | Vamsi Bhavani\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/watch?v=n0zEsDkwwQs\",\n      \"rating\": 4.0,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 403,\n      \"num_enrolled\": 511135,\n      \"is_free\": true,\n      \"duration_hours\": 0.38,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"Te\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 89.06,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"Databases and SQL for Data Science with Python\",\n      \"source\": \"coursera\",\n      \"url\": \"https://www.coursera.org/learn/sql-data-science\",\n      \"rating\": 4.7,\n      \"rating_source\": \"user_reviews\",\n      \"num_reviews\": 23000,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"data-science\",\n      \"has_certificate\": true,\n      \"engagement_proxy\": 62.9,\n      \"completeness_score\": 0.6667\n    },\n    {\n      \"title\": \"Python Programming Tutorial 🔥 Full Python Course for Beginners\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLwhVruPHD9rzDSsfS5ZKXrUPAo6I7RQEh\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.9333\n    },\n    {\n      \"title\": \"Python Language in Pashto For Beginners by Hassan\",\n      \"source\": \"youtube\",\n      \"url\": \"https://www.youtube.com/playlist?list=PLDdMcjWqAKJEY176iqh-QOjouaCItHZIh\",\n      \"rating\": 0.0,\n      \"rating_source\": \"unavailable\",\n      \"num_reviews\": 0,\n      \"num_enrolled\": 0,\n      \"is_free\": true,\n      \"duration_hours\": 0.0,\n      \"level_normalized\": \"Beginner\",\n      \"language_normalized\": \"English\",\n      \"category\": \"Python Programming\",\n      \"has_certificate\": false,\n      \"engagement_proxy\": 0.0,\n      \"completeness_score\": 0.8\n    }\n  ]\n}
""" # Your raw string

# Parse string into a dictionary
parsed_data = json.loads(json_string)

# Save to file with formatting (indent=4 makes it readable)
with open("data.json", "w", encoding="utf-8") as f:
    json.dump(parsed_data, f, indent=4)